services:
  tidefetch:
    environment:
      TIDEFETCH_PASSWORD: ""
      TIDEFETCH_PASSWORD_FILE: /run/secrets/web_password
    secrets:
      - web_password

secrets:
  web_password:
    file: ./secrets/web_password